### ISSUE TITLE
remove bootnode config in harbour

### ISSUE THREAD

**Issue by cgroeschel** [DataHighway-DHX/node#202]
https://github.com/DataHighway-DHX/node/blob/e3ddd0f2a35807fe75ff9dd665ad36cb51b1f0b0/node/src/chain_spec.rs#L780

the IP can change on instance restart, its now 3.67.168.170 and for harbour we don't have to buy a static IP unless really necessary

**Comment by ayushmishra2005** [comment]
@cgroeschel  I think this is done https://github.com/DataHighway-DHX/node/blob/master/node/src/chain_spec.rs#L779.

Can we close this?

cc @ltfschoen @jeffstahlnecker

**Comment by cgroeschel** [comment]
Yes, can be closed.
