### ISSUE TITLE
Harbour Payouts seem unusual high

### ISSUE THREAD

**Issue by ayushmishra2005** [DataHighway-DHX/node#208]
![image-20210505-154035](https://user-images.githubusercontent.com/1575561/122899268-4fdf6780-d369-11eb-9466-96fd98e4fcad.png)

**Comment by ltfschoen** [comment]
As you mentioned we'll go through the responses to the questions you raised:
https://github.com/paritytech/subport/issues/193#issuecomment-867735155
https://github.com/paritytech/subport/issues/192#issuecomment-867731964

**Comment by ayushmishra2005** [comment]
@ltfschoen In the above screenshot return of every validator is getting calculated here https://github.com/polkadot-js/apps/blob/d91bdcd191e7ca703fc7618188ab4a9a62763879/packages/page-staking/src/useSortedTargets.ts#L184-L192

`Return` depends on `Total Stake`.  As I checked the calculation, 

more stake => less return will be shown
less stake => more return will be shown

**Comment by ayushmishra2005** [comment]
@ltfschoen As discussed, I am closing this issue.
